# Generated by Django 5.2.7 on 2025-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sprofile',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
    ]
