# Generated by Django 5.2.7 on 2025-12-10 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_wishlist_ttime_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 10, 8, 41, 47, 625547, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 10, 8, 41, 47, 624898, tzinfo=datetime.timezone.utc)),
        ),
    ]
