# Generated by Django 5.2.7 on 2026-01-12 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_cart_ttime_alter_wishlist_ttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 12, 4, 0, 140143, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 12, 4, 0, 139492, tzinfo=datetime.timezone.utc)),
        ),
    ]
